### PR TITLE
Features

### LINKED ISSUE #78: Chapter 6: Broken Vagrant script with chef_solo provision failure
Current version of Vagrant 1.8.5 (on Virtualbox 5.1) throws the following error when provisioning (Ubuntu Precise):

==> default: Running provisioner: chef_solo...
    default: Installing Chef (latest)...
Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.

As far as I could track down the issue seems to with identification of the guest OS as linux instead of Ubuntu.

### PR DESCRIPTION
**Pull request by avtomato**
* fixed [error](https://github.com/semmypurewal/LearningWebAppDev/issues/78) "undefined method `nodejs' for {}:Chef::Node::VividMash"
* Updated to latest stable release of node
* Updated to latest stable release of redis
* Updated to latest stable release of ruby

### CODE REVIEW

**Comment by dan-doran** [comment]
Nice work!

I am getting this error:
`undefined method \`[]' for nil:NilClass`

**Comment by avtomato** [comment]
@dan-doran What stage of the installation causes this error?

**Comment by dan-doran** [comment]
I believe it was when Chef had just finished installing nodejs.

**Comment by vvteixeira** [comment]
It works for me! Thanks!!!

**Comment by semmypurewal** [comment]
Thanks for submitting this! Sorry it took so long for me to take a look at it.

I ended up fixing things by removing Chef altogether and just using the system-level stuff. Seems to work fine now, and is a little simpler to reason about. :)

Let me know if you have any other problems! And thanks again!

**Pull request closed without merging**
